global:
  scrape_interval: 10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['order-service:8200']
        labels:
          application: 'Order Service Application'
  - job_name: 'product-catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['product-catalog-service:8100']
        labels:
          application: 'Product Catalog Service Application'